### ISSUE TITLE
Comments, Disqus on static & portal

### ISSUE THREAD

**Issue by IrisDroidology** [acord-robotics/stellarios#19]
**What part of the network are you referring to in this issue?**
Portal, Netlify, & Github

**What is the purpose of this topic?**
Adding comment functionality to the sites mentioned above

**What have you done?**
The ACORD news site - http://acord.tech/news, on Github/Acord-Robotics/Acordnews) already has commenting functionality built in. However, we need to create a new site (sitename) with Disqus so that only comments on that site are visible.

I have tried following numerous tutorials on how to add commenting functionality to jekyll, however they haven't worked with the Hydejack theme that we are using on this repository and for Gitlab/Netlify

**What needs to be done?**
Create an issue on Github/Qwtel/Hydejack describing what I've done to *try* and get Disqus to work
Figure out how to add Disqus/other comment system to Jekyll
Add Disqus/other comment system to Portal

**Comment by IrisDroidology** [comment]
What we could do is have *another* site for Comments, using a theme that supports Disqus out of the box: https://github.com/sylhare/Type-on-Strap is an example

**Comment by IrisDroidology** [comment]
Disqus was added to the Portal - site name acordrobotics. I'll upload an image to the acord-portal branch, the link will be posted here as well

**Comment by IrisDroidology** [comment]
https://github.com/acord-robotics/acord-robotics/issues/5

**Comment by IrisDroidology** [comment]
The comments have been added using Graphcomments to the portal
No bootstrap support yet, or jekyll...disqus is probably the best option for jekyll

**Comment by mfaridn03** [comment]
We will embed the jekyll post on the ACORD portal, allowing the disqus/graphcomments to work on both
