### ISSUE TITLE
Acord-Games: Asteroid Dodgers Main Menu

### ISSUE THREAD

**Issue by IrisDroidology** [acord-robotics/stellarios#36]
https://www.youtube.com/watch?v=zc8ac_qUXQY

**Comment by mfaridn03** [comment]
The main menu has been created, however there is no quit functionality or options functionality. The "play game" option sends you to a level selector which is currently being built. Build 6 has been released

**Comment by IrisDroidology** [comment]
Check out the changelog here: https://acord-robotics.github.io/stellarios/asteroid-dodgers-changelog/

**Comment by IrisDroidology** [comment]
Main menu now has the "How to Play" (aka GameOptions scene) which links back to main menu

**Comment by IrisDroidology** [comment]
https://github.com/acord-robotics/unityballs/commit/bf05682f9800a43dbe565cf47959ec209dffe5e4
[Stellarios + AD + Build 6.2](https://github.com/acord-robotics/unityballs/commit/bf05682f9800a43dbe565cf47959ec209dffe5e4)
