### ISSUE TITLE
AWS #88 #89 - GazeboSim on Local Environemnt

### ISSUE THREAD

**Issue by IrisDroidology** [acord-robotics/stellarios#90]
https://github.com/EXYNOS-999/AWS_JPL_DRL/issues/2
https://github.com/EXYNOS-999/AWS_JPL_DRL/issues/3

I've got gazebo sim installed on my local env.

```
curl -sSL http://get.gazebosim.org | sh
```

This project is being put into the [`Arduino` branch](https://github.com/acord-robotics/stellarios/tree/_arduino).

See issues #89 #88

**Comment by IrisDroidology** [comment]
As gazebo is now installed, this issue can be marked as complete

**Comment by EXYNOS-999** [comment]
Which version of Gazebo have you installed?

**Comment by IrisDroidology** [comment]
I have 10.1 now, see our old slack and trello board. Linux & gazebo is now installed and the correct versions too! Linux Ubuntu 18.04 and GazeboSim.org 10.1

**Comment by IrisDroidology** [comment]
#88 & https://github.com/EXYNOS-999/AWS_JPL_OSR_DRL/issues/1

**Comment by IrisDroidology** [comment]
Report coming soon

**Comment by IrisDroidology** [comment]
We've got it set up, report is on `Exynos-999/AWS_JPL_OSR_DRL`
